version: "3.8"

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - TOTP_KEY=${TOTP_KEY}
      - DATABASE_URL=postgresql+asyncpg://trading_user:Charan123@postgres:5432/trading_bot
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAX_POSITION_SIZE=100000.0
      - MAX_DAILY_LOSS=10000.0
      - RISK_PERCENTAGE=2.0
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7.0
    ports:
      - "6380:6379" # Changed from 6379 to 6380
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=Charan123
      - POSTGRES_DB=trading_bot
    ports:
      - "5433:5432" # Changed from 5432 to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9091:9090" # Changed from 9090 to 9091
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3001:3000" # Changed from 3000 to 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  redis_data:
