global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'trading_bot'
    static_configs:
      - targets: ['trading_bot:8000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']